[build]
  # Build command
  command = "npm run build"
  
  # Publish directory (where the built files are) - Netlify preset uses dist/
  publish = "dist"
  
  # Node.js version and environment variables
  environment = { NODE_VERSION = "20", NODE_ENV = "production", CACHE_TTL = "86400000", API_COUNTRY = "us" }

# Production builds
[context.production]
  command = "npm run build"
  environment = { NODE_ENV = "production" }

# Deploy preview builds (for PRs)
[context.deploy-preview]
  command = "npm run build:preview"
  environment = { NODE_ENV = "staging" }

# Branch deploys (for feature branches)
[context.branch-deploy]
  command = "npm run build:staging"
  environment = { NODE_ENV = "staging" }

# Redirect rules for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache headers for static assets
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache"

# Build notifications
[build.processing]
  skip_processing = false

# Netlify plugins (commented out temporarily to fix deployment)
# [[plugins]]
#   package = "netlify-plugin-lighthouse"
#   
#   [plugins.inputs]
#     # Performance budgets
#     performance = 90
#     accessibility = 90
#     best_practices = 90
#     seo = 90
